import type { ListingDTO } from "@/lib/matches/types";

export const sampleListings: ListingDTO[] = [
  {
    id: "demo:1",
    url: null,
    price: 35000,
    price_display: "35,000",
    bhk: 2,
    bathrooms: 2,
    area_sqft: 1000,
    locality: "Salt Lake",
    furnishing: "Semi-Furnished",
    listing_type: "rent",
    property_type: "Apartment",
    possession: "Immediately",
    posted_at: null,
    reason: "Placeholder: why this listing fits.",
  },
  {
    id: "demo:2",
    url: null,
    price: 30000,
    price_display: "30,000",
    bhk: 3,
    bathrooms: 2,
    area_sqft: 1200,
    locality: "New Town",
    furnishing: "Furnished",
    listing_type: "rent",
    property_type: "Apartment",
    possession: "Immediately",
    posted_at: null,
    reason: "Placeholder: why this listing fits.",
  },
  {
    id: "demo:3",
    url: null,
    price: 26000,
    price_display: "26,000",
    bhk: 2,
    bathrooms: 2,
    area_sqft: 892,
    locality: "Ballygunge",
    furnishing: "Unfurnished",
    listing_type: "rent",
    property_type: "Apartment",
    possession: "Immediately",
    posted_at: null,
    reason: "Placeholder: why this listing fits.",
  },
  {
    id: "demo:4",
    url: null,
    price: 42000,
    price_display: "42,000",
    bhk: 3,
    bathrooms: 3,
    area_sqft: 1400,
    locality: "Salt Lake",
    furnishing: "Furnished",
    listing_type: "rent",
    property_type: "Apartment",
    possession: "Immediately",
    posted_at: null,
    reason: "Placeholder: why this listing fits.",
  },
  {
    id: "demo:5",
    url: null,
    price: 18000,
    price_display: "18,000",
    bhk: 1,
    bathrooms: 1,
    area_sqft: 600,
    locality: "New Town",
    furnishing: "Semi-Furnished",
    listing_type: "rent",
    property_type: "Studio",
    possession: "Immediately",
    posted_at: null,
    reason: "Placeholder: why this listing fits.",
  },
  {
    id: "demo:6",
    url: null,
    price: 33000,
    price_display: "33,000",
    bhk: 2,
    bathrooms: 2,
    area_sqft: 1100,
    locality: "Ballygunge",
    furnishing: "Furnished",
    listing_type: "rent",
    property_type: "Builder Floor",
    possession: "Immediately",
    posted_at: null,
    reason: "Placeholder: why this listing fits.",
  },
];
